<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.10</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.outman</groupId>
    <artifactId>engine-shit</artifactId>
    <version>${shit.version}</version>
    <name>engine-shit</name>
    <description>engine-shit</description>
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
    </dependencies>
    <packaging>pom</packaging>
    <properties>
        <java.version>17</java.version>
        <shit.version>0.0.1-SNAPSHOT</shit.version>
        <spring.boot.version>3.4.4</spring.boot.version>
    </properties>

    <modules>
        <module>engine-shit-common</module>
        <module>engine-shit-domain</module>
        <module>engine-shit-infrastructure</module>
        <module>engine-shit-service</module>
        <module>engine-shit-web</module>
        <module>engine-shit-start</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- 内部模块 -->
            <dependency>
                <groupId>com.outman</groupId>
                <artifactId>engine-shit-common</artifactId>
                <version>${shit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.outman</groupId>
                <artifactId>engine-shit-domain</artifactId>
                <version>${shit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.outman</groupId>
                <artifactId>engine-shit-infrastructure</artifactId>
                <version>${shit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.outman</groupId>
                <artifactId>engine-shit-service</artifactId>
                <version>${shit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.outman</groupId>
                <artifactId>engine-shit-web</artifactId>
                <version>${shit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring.boot.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-thymeleaf</artifactId>
                <version>${spring.boot.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <optional>true</optional>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
